[project]
name = "Estudo-Python"
version = "0.1.0"
description = "Estudos de conceitos de engenharia de software"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-p no:warnings"
